prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/credentials/credentials_for_mapquest.sql
@@application/shared_components/remote_servers/www_mapquestapi_com_geocoding_v1.sql
@@application/shared_components/data_profiles/mapquest.sql
@@application/shared_components/web_sources/mapquest.sql
@@application/shared_components/navigation/lists/wizard_progress_list.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/mobile_navigation_menu.sql
@@application/shared_components/files/js_display_shortcut_js.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/getimage.sql
@@application/shared_components/logic/application_items/file_id.sql
@@application/shared_components/logic/application_items/g_install_part_id.sql
@@application/shared_components/logic/application_items/g_order_id.sql
@@application/shared_components/logic/application_items/g_td_2.sql
@@application/shared_components/logic/application_items/g_td_3.sql
@@application/shared_components/logic/application_items/g_td_4.sql
@@application/shared_components/logic/application_items/g_td_5.sql
@@application/shared_components/logic/application_items/g_td_6.sql
@@application/shared_components/logic/application_items/g_today.sql
@@application/shared_components/logic/application_items/g_today_1.sql
@@application/shared_components/logic/application_items/g_today_2.sql
@@application/shared_components/logic/application_items/g_today_3.sql
@@application/shared_components/logic/application_items/g_today_4.sql
@@application/shared_components/logic/application_items/g_today_5.sql
@@application/shared_components/logic/application_items/g_today_6.sql
@@application/shared_components/logic/application_items/g_user_id.sql
@@application/shared_components/logic/application_items/g_user_territory.sql
@@application/shared_components/logic/application_items/g_week_1.sql
@@application/shared_components/logic/application_items/g_week_10.sql
@@application/shared_components/logic/application_items/g_week_12.sql
@@application/shared_components/logic/application_items/g_week_2.sql
@@application/shared_components/logic/application_items/g_week_3.sql
@@application/shared_components/logic/application_items/g_week_4.sql
@@application/shared_components/logic/application_items/g_week_5.sql
@@application/shared_components/logic/application_items/g_week_6.sql
@@application/shared_components/logic/application_items/g_week_7.sql
@@application/shared_components/logic/application_items/g_week_8.sql
@@application/shared_components/logic/application_computations/g_order_id.sql
@@application/shared_components/logic/application_computations/g_install_part_id.sql
@@application/shared_components/logic/application_computations/p0_new_messages.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/calendar_css_classes.sql
@@application/shared_components/user_interface/lovs/delivery_locations.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/init_or_follow.sql
@@application/shared_components/user_interface/lovs/installers.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/ship_to_locations.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/vendors.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/shared_components/user_interface/lovs/yes_no.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/dialog.sql
@@application/shared_components/user_interface/templates/page/page.sql
@@application/shared_components/user_interface/templates/page/popup.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/icon_button.sql
@@application/shared_components/user_interface/templates/button/standard_button.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/button_group_horizontal.sql
@@application/shared_components/user_interface/templates/region/button_group_vertical.sql
@@application/shared_components/user_interface/templates/region/collapsible_closed.sql
@@application/shared_components/user_interface/templates/region/collapsible_open.sql
@@application/shared_components/user_interface/templates/region/collapsible_set.sql
@@application/shared_components/user_interface/templates/region/footer_toolbar_displays_at_bottom_of_page.sql
@@application/shared_components/user_interface/templates/region/footer_toolbar_fixed.sql
@@application/shared_components/user_interface/templates/region/footer_toolbar_fullscreen.sql
@@application/shared_components/user_interface/templates/region/header_toolbar_fixed.sql
@@application/shared_components/user_interface/templates/region/header_toolbar_fullscreen.sql
@@application/shared_components/user_interface/templates/region/panel.sql
@@application/shared_components/user_interface/templates/region/plain_no_title.sql
@@application/shared_components/user_interface/templates/region/region_with_title_bar.sql
@@application/shared_components/user_interface/templates/region/region_with_title.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/button_control_group.sql
@@application/shared_components/user_interface/templates/list/list_view.sql
@@application/shared_components/user_interface/templates/list/list_view_inset.sql
@@application/shared_components/user_interface/templates/list/navigation_bar_002.sql
@@application/shared_components/user_interface/templates/list/navigation_menu.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/standard_report.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/no_label_for_screenreaders.sql
@@application/shared_components/user_interface/templates/label/optional_002.sql
@@application/shared_components/user_interface/templates/label/required_002.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/templates/calendar/basic_calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/ok_to_get_next_prev_pk_value.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/bb_custom_auth.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/shared_components/plugins/item_type/jd_input_item_mask.sql
@@application/shared_components/plugins/dynamic_action/auto_fade_success_message.sql
@@application/shared_components/plugins/item_type/ch_pure_apex_dynamic_quickpick.sql
@@application/shared_components/data_loads/tpt_phones.sql
@@application/shared_components/data_loads/tpt_raw_data.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00999.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00060.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00101.sql
@@application/pages/page_00500.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10011.sql
@@application/pages/page_10012.sql
@@application/pages/page_10013.sql
@@application/pages/page_10014.sql
@@application/pages/page_10020.sql
@@application/pages/page_10021.sql
@@application/pages/page_10023.sql
@@application/pages/page_10024.sql
@@application/pages/page_10100.sql
@@application/pages/page_10110.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
